### ISSUE TITLE
YogaNode does not expose the measure method

### ISSUE THREAD

**Issue by chrispytoes** [OrionCraftMC/meditate-layout#1]
`YogaNode` should expose the measure method. In my case, I need this for text wrapping, where the width needs to be calculated by Yoga during the measure function in order to wrap the text and figure out the height. Yoga already prevents infinite recursion when calling measure inside itself.

Can this be done by just adding it to the `YogaNode` interface, or does it need to be regenerated from the C++? I'm not sure how this converter works.

**Comment by chrispytoes** [comment]
@NickAcPT I've managed to add the measure method myself and write a test for it [here](https://github.com/chrispytoes/meditate-layout/tree/self-measure).

However the issue is that this causes infinite recursion. Calling `node.measure` within your own measure function should call the base default measure function instead of your custom one. Is this possible to fix easily?

**Comment by NickAcPT** [comment]
@chrispytoes apologies for not replying any sooner!

> Can this be done by just adding it to the `YogaNode` interface, or does it need to be regenerated from the C++? I'm not sure how this converter works.

This project was first started by using an automated code conversion tool, then the code was fixed so that it compiled, thus no converter is involved anymore, so it is as easy as editing the Java code present.

> Yoga already prevents infinite recursion when calling measure inside itself.

Do you happen to know when this behaviour was introduced into Yoga? This fork is _a bit_ out of date 😅  

> Calling `node.measure` within your own measure function should call the base default measure function instead of your custom one. Is this possible to fix easily?

I don't know whether this will be easy to fix easily without having a way to explicitly call the base measuring function.

If this were a simple overridden method, one could use a `super.` call, but since the original Yoga code used function pointers; and here they were converted to normal Java lambdas; we don't have that option directly.
I have asked a friend and will update if anything comes up, although if you manage to get it working, do let me know and shoot a PR my way and I'll get it published.

**Comment by chrispytoes** [comment]
@NickAcPT Honestly I'll admit, I couldn't find much of any examples on how to use Yoga, and I don't know C++ so I asked ChatGPT and it told me about the recursion thing 😅

Just did a test and realized it still calls the base measure logic if I just add a condition to prevent the recursion myself. So yeah that solves my issue 🤣

**Comment by chrispytoes** [comment]
@NickAcPT My bad spoke too soon, the measure function still need to be exposed. My code does that already so I'll make a PR.

**Comment by chrispytoes** [comment]
@NickAcPT Thank you so much! Will this be pushed to Maven as well?

**Comment by NickAcPT** [comment]
@chrispytoes Yeah, I've merged the PR and bumped the version.

It's been pushed to the repo with the version `1.0.2`, it should be available now.
